print("--- Fill up Form ---\n")
Name = input("What is your name? ")
Age = input("How old are you? ")
Gender = input("What is your gender? ")
MonthBirth = input("In what month were you born? ")
YearBirth = int(input("In what year were you born? "))
DayBirth = input("On what day of the month were you born? ")
Nationality = input("What is your nationality? ")
Address = input("What is your current address? ")
PlaceBirth = input("Where were you born? ")
Height = int(input("What is your height in cm? "))
Weight = int(input("What is your weight in kg? "))
ContactNumber = input("What is your contact number? ")
Religion = input("What is your religion? ")
MothersName = input("What is your mother's name? ")
FathersName = input("What is your father's name? ")
College = input("Which college or university do you attend? ")
Program = input("What program or course are you taking? ")
print("\n------------------------")
print(Name, "is a", str(Age), "year old", Gender, "from", PlaceBirth, "living at", Address + ".")
print("Born on", MonthBirth, DayBirth, ",", str(YearBirth), ", they hold", Nationality, "citizenship and practice", Religion + ".")
print("They stand", str(Height), "tall, weighing", str(Weight), "kg, and can be reached or contacted at", ContactNumber + ".")
print("The child of", FathersName, "and", MothersName + ".")
print("Currently enrolled as", Program, "at", College + ".")

